# Automatically pull changes to the demo site from the main 'esbonio' repo.
name: 'Update Demo'
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'alcarney/esbonio'
        ref: 'demo'
        path: 'esbonio'

    - uses: actions/checkout@v4
      with:
        path: 'demo'

    - run: |
        set -eux
        rsync -av --delete --exclude=.git* esbonio/lib/esbonio/tests/workspaces/demo/ demo

        git -C demo config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git -C demo config user.name "github-actions[bot]"

        git -C demo add .
        git -C demo commit -am "Sync demo content"
        git -C demo log -1
      name: Sync content
